---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров  
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit: 
  - Пользователь должен иметь возможность зарегистрироваться и войти в систему, просматривать и редактировать свой профиль
  - Сайт должен поддерживать различные способы оплаты
  - Пользователь должен иметь возможность заказать товар и получать уведомления о статусе своего заказа
  - Сайт должен предоставлять возможность связаться с поддержкой клиентов
  - Сайт должен поддерживать несколько языков и региональных настроек
  - Сайт должен быть оптимизирован для поисковых систем
  - Сайт должен собирать данные о поведении пользователей для анализа
  - Сайт должен быть доступен для пользователей с ограниченными возможностями
